apiVersion: v1
kind: PersistentVolume
metadata:
  name: playground-pv
  labels:
    type: local
spec:
  storageClassName: playground-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /playground
